# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      is_key_content_base64: true,
      in_house: false # detecting this via ASC private key not currently supported
    )
  end

  desc "Description of what the lane does"
  lane :main_development do
    puts "[fosscat]: Calling match to get signing certificates/profiles..."
    match(readonly: true)

    puts "[fosscat]: Loading App Store Connect API key"
    load_asc_api_key

    puts "[fosscat]: Syncing code signing certificates/profiles..."
    sync_code_signing(type: "development")
    
    puts "[fosscat]: Disabling automatic code signing, setting bundle identifier..."
    update_code_signing_settings(
      # use_automatic_signing: false, - default
      path: "./ios/fosscat.xcodeproj",
      bundle_identifier: "net.jcxldn.fosscat"
    )

    puts "[fosscat]: Setting project team..."
    update_project_team(
      path: "./ios/fosscat.xcodeproj",
      teamid: "ZK8CX5A77V"
    )

    puts "[fosscat]: Building application..."
    build_app(
      scheme: "fosscat",
      workspace: "./ios/fosscat.xcworkspace",
      export_method: "development",
      export_options: {
        provisioningProfiles: {
          "net.jcxldn.fosscat" => "match Development net.jcxldn.fosscat"
        }
      }
    )
  end
end
