package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"log"

	"github.com/google/uuid"
	"github.com/jcxldn/fosscat/backend/graph/model"
	"github.com/jcxldn/fosscat/backend/structs"

	emailverifier "github.com/AfterShip/email-verifier" // Email verifier library
)

var (
	verifier = emailverifier.NewVerifier()
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*structs.User, error) {
	// Create a User struct from the input model
	// Set fields that do not need further validation (name only)
	user := structs.User{FirstName: input.FirstName, LastName: input.LastName}

	// Attempt to validate the user email.
	res, err := verifier.Verify(input.Email)
	//res.
	if err != nil {
		// Email address failed to verify
		// TODO: make errors more readable, custom errors.
		log.Fatalln("[createUser] email address failed to verify")
		return nil, err
	}

	if !res.Syntax.Valid {
		// Email address is not valid
		// TODO: make errors more readable, custom errors.
		return nil, err
	}

	// Email passed validation, set in the user struct.
	user.Email = res.Email

	// Generate a UUID for the user id.
	user.ID = uuid.New()

	// Salt and hash the provided password

	r.db.Create(&user)
	return &structs.User{ID: user.ID, FirstName: user.FirstName, LastName: user.LastName, Email: user.Email}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*structs.User, error) {
	// Get all users. POC only, returns everything!
	users := []*structs.User{}
	result := r.db.Find(&users)
	return users, result.Error
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *structs.User) (string, error) {
	return obj.ID.String(), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
