"The `Upload` scalar type represents a multipart file upload."
scalar Upload


enum FileTypes {
    ERROR_DETERMINING,
    GENERIC,
    IMAGE
}

type File {
    id: String!
    uploader: User!
    name: String!
    data: String!
    type: FileTypes!
}

input UploadFile {
    id: Int!
    file: Upload!
}