type Mutation {
  createCheckout(input: NewCheckout!): Checkout!
  createEntity: Entity!
  createItem(input: NewItem!): Item!
  createUser(input: NewUser!): User!

  login(email: String!, password: String!): LoginResponse!
  loginRefresh(refresh: String!): LoginResponse!
}