type User {
  id: String!
  firstName: String!
  lastName: String!
  email: String!
  hash: String
}

input NewUser {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}

input ExistingUser {
  id: String!
}